"""Central path definitions for the project."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

SRC_DIRECTORY = PROJECT_ROOT / "src"
PAGES_DIRECTORY = PROJECT_ROOT / "pages"
DATA_DIRECTORY = PROJECT_ROOT / "data"
RAW_DATA_DIRECTORY = DATA_DIRECTORY / "raw"
PROCESSED_DATA_DIRECTORY = DATA_DIRECTORY / "processed"
CHECKPOINT_DIRECTORY = DATA_DIRECTORY / "checkpoints"
REPORTS_DIRECTORY = DATA_DIRECTORY / "reports"
DATA_EVALUATION_DIRECTORY = DATA_DIRECTORY / "evaluation"
DATA_DIRECTORY = PROJECT_ROOT / "data"
RAW_DATA_DIRECTORY = DATA_DIRECTORY / "raw"
PROCESSED_DATA_DIRECTORY = DATA_DIRECTORY / "processed"
CHECKPOINT_DIRECTORY = DATA_DIRECTORY / "checkpoints"
REPORTS_DIRECTORY = DATA_DIRECTORY / "reports"
DATA_EVALUATION_DIRECTORY = DATA_DIRECTORY / "evaluation"
CACHE_DIRECTORY = DATA_DIRECTORY / "cache"

MODELS_DIRECTORY = PROJECT_ROOT / "models"
MERGE_OUTCOME_MODELS_DIRECTORY = MODELS_DIRECTORY / "merge_outcome"
MERGE_DELAY_MODELS_DIRECTORY = MODELS_DIRECTORY / "merge_delay"

KNOWLEDGE_BASE_DIRECTORY = PROJECT_ROOT / "knowledge_base"
EVALUATION_DIRECTORY = PROJECT_ROOT / "evaluation"
LOG_DIRECTORY = PROJECT_ROOT / "logs"
POLICIES_DIRECTORY = PROJECT_ROOT / "policies"
NOTEBOOKS_DIRECTORY = PROJECT_ROOT / "notebooks"


REQUIRED_DIRECTORIES = [
    DATA_DIRECTORY,
    RAW_DATA_DIRECTORY,
    PROCESSED_DATA_DIRECTORY,
    CHECKPOINT_DIRECTORY,
    REPORTS_DIRECTORY,
    DATA_EVALUATION_DIRECTORY,
    CACHE_DIRECTORY,
    MODELS_DIRECTORY,
    MERGE_OUTCOME_MODELS_DIRECTORY,
    MERGE_DELAY_MODELS_DIRECTORY,
    KNOWLEDGE_BASE_DIRECTORY,
    EVALUATION_DIRECTORY,
    LOG_DIRECTORY,
    POLICIES_DIRECTORY,
    NOTEBOOKS_DIRECTORY,
]


def create_required_directories() -> None:
    """Create all required project directories."""

    for directory in REQUIRED_DIRECTORIES:
        directory.mkdir(
            parents=True,
            exist_ok=True,
        )
